# Site settings
title:
email: yoselin.arvelaiz7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username: yoselin-arvelaiz
github_username: Yoselin-Arvelaiz7

# Build settings
markdown: kramdown
